site_title = "robotArxiv"
limit_days = 30
cache_url = "https://XinZhaoDC.github.io/robotArxiv/cache.json"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
